spring.cloud.stream.bindings.output.contentType: application/json
spring.cloud.stream.kstream.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kstream.binder.configuration:
  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  default.value.serde: org.apache.kafka.common.serialization.Serdes$IntegerSerde
  application.id: default
spring.cloud.stream.bindings.output:
  destination: counts
  producer:
    headerMode: raw
    #useNativeEncoding: true
spring.cloud.stream.bindings.input:
  destination: words
  group: group1
  consumer:
    headerMode: raw
    useNativeDecoding: true
spring.cloud.stream.kstream.bindings.input.consumer.dlqName: words-count-dlq
spring.cloud.stream.kstream.binder:
  brokers: localhost #192.168.99.100
  zkNodes: localhost #192.168.99.100
  serdeError: sendToDlq



