spring.cloud.stream.bindings.output1.contentType: application/json
spring.cloud.stream.bindings.output2.contentType: application/json
spring.cloud.stream.bindings.output3.contentType: application/json
spring.cloud.stream.kstream.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kstream.binder.configuration:
  key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.bindings.output1:
  destination: counts
  producer:
    headerMode: raw
spring.cloud.stream.bindings.output2:
  destination: foo
  producer:
    headerMode: raw
spring.cloud.stream.bindings.output3:
  destination: bar
  producer:
    headerMode: raw
spring.cloud.stream.bindings.input:
  destination: words
  group: group1
  consumer:
    headerMode: raw
spring.cloud.stream.kstream.binder:
  brokers: localhost #192.168.99.100
  zkNodes: localhost #192.168.99.100